routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::middleware(['auth'])->group( function() {
    //semua dalam ni wajib login

    Route::resource('projects', 'ProjectController');

    Route::resource('states','StateController');

});

Route::get('query1', 'ProjectController@query1');
Route::get('query2', 'ProjectController@query2');
Route::get('query3', 'ProjectController@query3');
Route::get('query4', 'ProjectController@query4');
   

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use App\Model\Project;
use App\Model\City;
use Illuminate\Http\Request;
use App\Http\Requests\Project\Store;
use App\Http\Requests\Project\Update;
use Illuminate\Support\Facades\Storage;


class ProjectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    { 
        // with() <-- eager loading. 
        //            code akan dapatkan terus data berkait.
        // 
        // takde with() <-- lazy loading.
        //                  data dia query semasa digunakan   

        $search = request()->search;

        $project_city_ids = [];
        if($search) {
            $project_city_ids = Project::where('name', 'like', '%' . $search . '%')
                                    ->orWhere('detail', 'like', '%' . $search . '%')
                                    ->get()
                                    ->pluck('city_id')
                                    ->toArray()
                                    ;
        }
        

        $cities = City::with('projects')
                        ->when($search, function($query) use ($search) { 
                            $query->where('name', 'like', '%' . $search . '%');
                        })
                        // ->when($project_city_ids, function($query) use ($project_city_ids) {
                        //     $query->has('projects', function($query) use ($project_city_ids) {                                
                        //             $query->whereIn('city_id', $project_city_ids);
                        //     });
                        
                        // })
                        ->orderBy('name')
                        ->get();

        //$projects = Project::get();
        
        return view('project.index', ['cities' => $cities]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $cities = City::get();
        $user = User::get();
        return view('project.create', compact('cities','user') );
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Store $request)
    {

        $project = new Project();

        $project->name = request()->name;
        $project->detail = $request->detail;
        $project->user_id = \Auth::user()->id; //id of current logged in user

        $project->save();

        return redirect( route('projects.index') );
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Model\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $project = Project::findOrFail($id);
        return view('project.show', ['project' => $project ] );
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Model\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function edit(Project $project)
    {
        return view('project.edit', ['project' => $project ] );

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Model\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function update(Update $request, Project $project)
    {
        //use Illuminate\Support\Facades\Storage;

        if( request()->has('delete_proj_doc') ) {
            //delete bila ada orang tick checkbox delete file
            Storage::disk('public')->delete( $project->proj_doc);
            $project->proj_doc = null;
        }

        // Request::hasFile() <-- check if ada upload file
        if( request()->hasFile('proj_doc') ) {
            //if ada update file, delete file lama
            Storage::disk('public')->delete( $project->proj_doc);

            $path = request()->file('proj_doc')
                        ->store('projects','public');
            $project->proj_doc = $path;
        }

        $project->name = request()->name;
        $project->detail = $request->detail;
        $project->user_id = $request->user_id;

        $project->save();

        \Session::flash('alert', [
                'type' => 'success',
                'message' => 'Rekod berjaya dikemaskini',
                ] );

        return redirect( route('projects.index') );
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Model\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function destroy(Project $project)
    {

        $project->delete();
        return redirect( route('projects.index') );

    }

    public function query1() {
        // SELECT * 
        // FROM projects
        // WHERE 1=1
        // AND id > 2
        // AND id < 5
        
        return Project::where('id', '>', 2)
                        ->where('id', '<', 5)
                        ->get();
    }

    public function query2() {
        /*
         SELECT projects.*, users.* 
         FROM projects
         LEFT JOIN users ON ( users.id = projects.user_id 
                            AND  users.name = 'zamrul')
         WHERE 1=1 
         AND WHERE users.id NOT NULL
         AND WHERE users.name = 'zamrul'
        */

        $city_ids = City::where('name','Cyberjaya')
        ->get()
        ->pluck('id')
        ->toArray();

        $projects = Project::with([ 
                            'bandar',
                             'owner' => function($query) {
                                $query->where('name', 'zamrul');
                             }, 
                             'owner.projects',
                             ])
                        ->whereHas('owner', function($query) {
                            $query->where('name','admin');
                        })
                        ->whereIn('city_id',$city_ids )
                        // ->whereHas('bandar', function($query) {
                        //     $query->where('name','Cyberjaya');
                        // }) // tak akan jalan sebab dalam DB lain 
                        ->get();

        return $projects;

    }

    public function query3() {
        // SELECT * 
        // FROM projects
        // WHERE 1=1
        // AND ( id > 2 OR id < 5 )
        // OR name LIKE '%ada%'
        
        return Project::where(function($query) {
                           $query->where('id', '>', 2)
                            ->orWhere('id', '<', 5);
                        })
                        ->where('name', 'like', '%ada%' )
                        ->get();
    }

    public function query4() {
        // SELECT count('id') as project_count, city_id
        // FROM projects
        // GROUP BY city_id

        return Project::select(\DB::raw("count('id') as project_count, city_id"))
                        ->groupBy('city_id')
                        ->with('bandar')
                        ->get();
    }

    //web.php
    // http://sukarelawan.test/query2
    // Route::get('query1', 'ProjectController@query1');
    // Route::get('query2', 'ProjectController@query2');
    // Route::get('query3', 'ProjectController@query3');
}

resources/views/project/create.blade.php
@extends('layouts.app')

@section('content')

<form method="POST" action="{{ route('projects.store') }}">
    @csrf
  <div class="form-group">
    <label for="name">{{ __("Name") }}</label>
    <input type="text" 
        class="form-control" 
        id="name" 
        aria-describedby="name"
        name="name"
        value="{{ old('name') }}"
    >
    @error('name')
      <div class="alert alert-danger">{{ $message }}</div>
    @enderror
  </div>
    
  <div class="form-group">
    <label for="name">{{ __("Detail") }}</label>
    <input type="text" 
        class="form-control" 
        id="detail" 
        aria-describedby="detail"
        name="detail"
        value="{{ old('detail') }}"
    >
    @error('detail')
      <div class="alert alert-danger">{{ $message }}</div>
    @enderror
  </div>

  <div class="form-group">
  <label for="user_id">{{ __("User") }}</label>
    <input type="text" 
        class="form-control" 
        id="user_id" 
        aria-describedby="user_id"
        name="user_id"
        value="{{ old('user_id') }}"    
    >
    @error('user_id')
      <div class="alert alert-danger">{{ $message }}</div>
    @enderror
  </div>


  <div class="form-group">
  <button class="btn btn-primary">{{ __("Submit") }} </button>
  </div>
</form>

@endsection

resources/views/project/edit.blade.php
@extends('layouts.app')

@section('content')

<form method="POST" 
  action="{{ route('projects.update', $project->id) }}"
  enctype="multipart/form-data"  
>
    @csrf
    @method('PUT')
  
  <div class="form-group">
    <label for="proj_doc">{{ __("Dokumen Projek") }}</label>
    <input type="file" 
        class="form-control-file" 
        id="proj_doc" 
        aria-describedby="proj_doc"
        name="proj_doc"
        value="{{ old('proj_doc', $project->proj_doc)  }}"
    >

    @if($project->proj_doc)
        <a href="{{ url('storage/' . $project->proj_doc) }}" 
            target="_BLANK" >Download</a>

        <input type='checkbox' name="delete_proj_doc" value="1" /> Check to delete   
    @endif

    @error('proj_doc')
      {{ $message }}
    @enderror
  </div>

  <div class="form-group">
    <label for="name">{{ __("Name") }}</label>
    <input type="text" 
        class="form-control" 
        id="name" 
        aria-describedby="name"
        name="name"
        value="{{ old('name', $project->name)  }}"
    >
    @error('name')
      {{ $message }}
    @enderror
  </div>

  <div class="form-group">
    <label for="detail">{{ __("Detail") }}</label>
    <input type="text" 
        class="form-control" 
        id="detail" 
        aria-describedby="detail"
        name="detail"
        value="{{ old('detail', $project->detail)  }}"
    >
    @error('detail')
      {{ $message }}
    @enderror
  </div>

  <div class="form-group">
    <label for="user_id">{{ __("User") }}</label>
    <input type="text" 
        class="form-control" 
        id="user_id" 
        aria-describedby="user_id"
        name="user_id"
        value="{{ old('user_id', $project->user_id)  }}"
    >
    @error('user_id')
      {{ $message }}
    @enderror
  </div>

  <div class="form-group">
  <button class="btn btn-primary">{{ __("Submit") }} </button>
  </div>
</form>

@endsection

resources/views/project/index.blade.php
@extends('layouts.app')

@section('content')

<div class="rows">
<form action="">
    <div class="col-md-6">
        <input type="text" name="search" value="{{ old('search') }}" class="form-control">
    </div>
    <div class="col-md-6">
        <input type="submit" value="Cari" class="btn btn-primary">
    </div>
</form>
</div>

<table class="table table-striped table-dark">
    <tr>
        <th>City</th>
        <th>Name</th>
        <th>Detail</th>
        <th>File</th>
        <th>User</th>
        <th></th>
    </tr>

    @foreach($cities as $city)
        @foreach($city->projects as $project)

        <tr>
            <td>{{ $city->name }}</td>
            <td>{{ $project->name }}</td>
            <td>{{ $project->detail }}</td>
            <td>
                @if($project->proj_doc)
                    <a href="{{ url('storage/' . $project->proj_doc) }}" 
                        target="_BLANK" >Download</a>
                @endif
            </td>
            <td>{{ $project->owner->name ?? '' }}</td>
            <td>
            <a class="btn btn-primary" href="{{ route('projects.show', $project->id) }}"> {{ __('View') }} </a>
            <a class="btn btn-primary" href="{{ route('projects.edit', $project->id) }}"> {{ __('Edit') }} </a>
            <a class="btn btn-warning" href="#" onclick="$('#del_{{ $project->id }}' ).submit()" > 
                {{ __('Delete') }} 
            </a>

            <form method="POST" id="del_{{ $project->id }}" 
                action="{{ route('projects.destroy', $project->id) }}">
                @csrf 
                @method('DELETE') 
            </form>
            </td>
        </tr>

        @endforeach
    @endforeach

</table>

@endsection

@section('script')

    <script>
        console.log("Hello world");
    </script>

@endsection

resources/views/project/show.blade.php
@extends('layouts.app')

@section('content')
<div class="card">
    <ul>
        <li> {{ __('Name') }} : {{ $project->name }} </li>
        <li> {{ __('Detail') }} : {{ $project->detail }} </li>
        <li> {{ __('User') }} : {{ $project->user_id }} </li>
    </ul>
</div>

@endsection