routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::middleware(['auth'])->group( function() {
    //semua dalam ni wajib login

    Route::resource('projects', 'ProjectController');

    Route::resource('states','StateController');

});

Route::get('query1', 'ProjectController@query1');
Route::get('query2', 'ProjectController@query2');
Route::get('query3', 'ProjectController@query3');
Route::get('query4', 'ProjectController@query4');
   

app/Http/Controllers/StateController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Model\State;

class StateController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $states = State::get();
        
        return view('state.index', compact('states') );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('state.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $state = new State();
        $state->code = $request->code;
        $state->name = $request->name;

        $state->save();

        return redirect(route('states.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $state = State::find($id);
        return view('state.show', compact('state'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $state = State::find($id);
        return view('state.edit', compact('state'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $state = State::find($id);

        $state->code = $request->code;
        $state->name = $request->name;

        $state->save();

        return redirect(route('states.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $state = State::find($id);

        $state->delete();

        return redirect(route('states.index'));
    }
}

resources/views/state/create.blade.php
@extends('layouts.app')

@section('content')

<form method="POST" action="{{ route('states.store') }}">
    @csrf
  <div class="form-group">
    <label for="code">{{ __("Code") }}</label>
    <input type="text" 
        class="form-control" 
        id="code" 
        aria-describedby="code"
        name="code"
        value="{{ old('code') }}"
    >
  </div>

  <div class="form-group">
  <label for="code">{{ __("Name") }}</label>
    <input type="text" 
        class="form-control" 
        id="name" 
        aria-describedby="name"
        name="name"
        value="{{ old('name') }}"
        required
    >
  </div>

  <div class="form-group">
  <button class="btn btn-primary">{{ __("Submit") }} </button>
  </div>
</form>

@endsection

resources/views/state/edit.blade.php
@extends('layouts.app')

@section('content')

<form method="POST" action="{{ route('states.update', $state->id) }}">
    @csrf
    @method('PUT')
  
  <div class="form-group">
    <label for="code">{{ __("Code") }}</label>
    <input type="text" 
        class="form-control" 
        id="code" 
        aria-describedby="code"
        name="code"
        value="{{ old('code') ?? $state->code }}"
    >
  </div>

  <div class="form-group">
  <label for="code">{{ __("Name") }}</label>
    <input type="text" 
        class="form-control" 
        id="name" 
        aria-describedby="name"
        name="name"
        value="{{ old('name') ?? $state->name }}"
        required
    >
  </div>

  <div class="form-group">
  <button class="btn btn-primary">{{ __("Submit") }} </button>
  </div>
</form>

@endsection

resources/views/state/index.blade.php
@extends('layouts.app')

@section('content')

<table class="table table-striped table-dark">
    <tr>
        <th>Code</th>
        <th>Name</th>
        <th></th>
    </tr>

    @foreach($states as $state)

    <tr>
        <td>{{ $state->code }}</td>
        <td>{{ $state->name }}</td>
        <td>
        <a class="btn btn-primary" href="{{ route('states.show', $state->id) }}"> {{ __('View') }} </a>
        <a class="btn btn-primary" href="{{ route('states.edit', $state->id) }}"> {{ __('Edit') }} </a>
        <a class="btn btn-warning" href="#" onclick="$('#del_{{ $state->id }}' ).submit()" > 
            {{ __('Delete') }} 
        </a>

        <form method="POST" id="del_{{ $state->id }}" 
            action="{{ route('states.destroy', $state->id) }}">
            @csrf 
            @method('DELETE') 
        </form>
        </td>
    </tr>

    @endforeach

</table>

@endsection

@section('script')

    <script>
        console.log("Hello world");
    </script>

@endsection

resources/views/state/show.blade.php
@extends('layouts.app')

@section('content')

<ul>
    <li> {{ __('Code') }} : {{ $state->code }} </li>
    <li> {{ __('Name') }} : {{ $state->name }} </li>
</ul>

@endsection